# Generated by Django 3.2.8 on 2021-10-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
