# Generated by Django 3.2.8 on 2021-10-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notice_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('username', models.CharField(max_length=500, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
